{% set name = "vacumm" %}
{% set version = "3.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7107752876047704bd122524bc4a95eaf48ce7bcda6ea8a6e0cda81d1e6be654

build:
  number: 0
  #script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [win or py3k or np<111]

requirements:
  build:
    - libgfortran
    #- {{ compiler('fortran') }} # not working for unknown reason
  host:
    - python
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cdms2
    - cdutil
    - genutil
    - matplotlib
    - cmocean
    - basemap
    - basemap-data-hires
    - configobj
    - pytz
    - paramiko
    - xlutils
    - seawater
    - scipy

test:
  imports:
    - vacumm
    - vcmq
  requires:
    - pytest
  commands:
    - pytest test
  source_files:
    - test/*.py
    - scripts/test/*
    - data/*

about:
  home: http://www.ifremer.fr/vacumm
  license: CeCiLL-2.1
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python library for ocean sciences'

  description: |
    VACUMM provides generic and specialized tools for the validation of ocean
    models, and more especially the MARS model from IFREMER.
    The heart of VACUMM is a library written mainly in the Python language,
    whose core can be used for the preprocessing and the postprocessing of
    oceanic and atmospheric data coming from models or observations.
    The library for instance also has specialized modules for managing
    outputs from models and making advanced diagnostics.
  doc_url: http://www.ifremer.fr/vacumm
  dev_url: https://github.com/VACUMM/vacumm

extra:
  recipe-maintainers:
    - stefraynaud
